@baseUrl = http://localhost:3000/api
@userUrl = {{baseUrl}}/user
### check server
get {{baseUrl}}

### signup
post {{userUrl}}/signup
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com",
    "password": "password123",
    "phone": "1234567890",
    "address": "123 Main St, Anytown, USA"
}
### login
post {{userUrl}}/login
Content-Type: application/json

{
    "email": "john.doe@example.com",
    "password": "password123"  
}



